apiVersion: v1
kind: Secret
metadata:
  name: counter-database
type: Opaque
data:
  database-host: Y291bnRlci1kYXRhYmFzZQ==
  database-name: Y291bnRlcl9kYXRhYmFzZQ==
  database-password: MTIzNDU=
  database-user: Y291bnRlcl91c2Vy
